refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.6f)} [{t}:{T}:{f}:{L}:{l}]: {m}{n}"
  p2p_poc:
    kind: file
    path: "log/p2p_poc.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.6f)} [{t}:{T}:{f}:{L}:{l}]: {m}{n}"
root:
  level: warn
  appenders:
    - stdout
loggers:
  p2p_poc:
    level: debug
    appenders:
      - stdout
    additive: false